services:
  - type: web
    name: kos-2
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
    autoDeploy: true

  - type: web
    name: kos-frontend
    env: static
    buildCommand: null
    staticPublishPath: frontend/public
    branch: main
    envVars:
      - key: BACKEND_URL
        value: https://kos-2.onrender.com
    autoDeploy: true
