services:
  - type: web
    name: kos-2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
    disk:
      name: uploads
      mountPath: /opt/render/project/src/uploads
      sizeGB: 1

  - type: static
    name: kos-frontend
    buildCommand: null
    staticPublishPath: ./frontend/public
    envVars:
      - key: BACKEND_URL
        value: https://kos-2.onrender.com
