services:
  - type: web
    name: kosge-backend
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
    autoDeploy: true

  - type: web
    name: kos-frontend-kqxo
    runtime: static
    buildCommand: echo "No build needed"
    staticPublishPath: frontend/public
    branch: main
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
